In [1]:
data_files = ["../datasets/mnli/multinli_1.0_dev_matched.jsonl.small.jsonl",
              "../datasets/mnli/multinli_1.0_dev_mismatched.jsonl.small.jsonl",
              "../datasets/mnli/snli_1.0_dev.jsonl.small.jsonl"
              ]

models_score_jsons_path =  "../temp/mnli/all_scores.json"

In [2]:
import pandas as pd


def load(datasets):
    result = []
    for l in datasets:
        df = pd.read_json(l, lines=True)
        df["dataset"] = l.split("/")[-1]
        result.append(df)

    df = pd.concat(result)

    # Remove invalid values
    df = df[df["gold_label"].isin(["entailment", "neutral", "contradiction"])].copy()
    return df


df = load(data_files)
df.sample(n=5)

,gold_label,annotator_labels,pairID,promptID,dataset,captionID
5284,entailment,"[entailment, entailment, entailment, entailmen...",4464415997.jpg#1r1e,NaN,snli_1.0_dev.jsonl.small.jsonl,4464415997.jpg#1
3950,entailment,"[entailment, entailment, entailment, entailmen...",80533e,80533.0,multinli_1.0_dev_mismatched.jsonl.small.jsonl,NaN
6167,contradiction,"[contradiction, contradiction, contradiction, ...",4502489690.jpg#4r1c,NaN,snli_1.0_dev.jsonl.small.jsonl,4502489690.jpg#4
3383,entailment,"[entailment, entailment, entailment, neutral, ...",209604956.jpg#0r1e,NaN,snli_1.0_dev.jsonl.small.jsonl,209604956.jpg#0
5703,neutral,"[neutral, entailment, neutral, neutral, neutral]",123891n,123891.0,multinli_1.0_dev_matched.jsonl.small.jsonl,NaN

In [3]:
df.describe()

            promptID
count   19647.000000
mean    73271.192192
std     42240.182714
min        14.000000
25%     36666.000000
50%     72940.000000
75%    110036.000000
max    146129.000000

In [4]:
from collections import Counter
import random


def add_column_pd(df):
    df["pd"] = df["annotator_labels"].apply(lambda x: Counter(x).most_common()[0][1] / len(x))
    df["majority_label"] = df["annotator_labels"].apply(lambda x: Counter(x).most_common()[0][0])
    return df


def add_column_anotherhuman(df, num_iterations=5):
    for i in range(num_iterations):
        df[f"another_human_{i}"] = df["annotator_labels"].apply(lambda x: random.sample(x, 1)[0])
    return df

In [5]:
df = df.pipe(add_column_pd) \
    .pipe(add_column_anotherhuman)
df.head()

,gold_label,annotator_labels,pairID,promptID,dataset,captionID,pd,majority_label,another_human_0,another_human_1,another_human_2,another_human_3,another_human_4
0,neutral,"[neutral, entailment, neutral, neutral, neutral]",63735n,63735.0,multinli_1.0_dev_matched.jsonl.small.jsonl,NaN,0.8,neutral,entailment,neutral,neutral,entailment,entailment
1,contradiction,"[contradiction, contradiction, contradiction, ...",91383c,91383.0,multinli_1.0_dev_matched.jsonl.small.jsonl,NaN,1.0,contradiction,contradiction,contradiction,contradiction,contradiction,contradiction
2,entailment,"[entailment, entailment, entailment, entailmen...",755e,755.0,multinli_1.0_dev_matched.jsonl.small.jsonl,NaN,1.0,entailment,entailment,entailment,entailment,entailment,entailment
3,contradiction,"[contradiction, contradiction, contradiction, ...",78013c,78013.0,multinli_1.0_dev_matched.jsonl.small.jsonl,NaN,1.0,contradiction,contradiction,contradiction,contradiction,contradiction,contradiction
4,contradiction,"[contradiction, contradiction, contradiction, ...",96377c,96377.0,multinli_1.0_dev_matched.jsonl.small.jsonl,NaN,1.0,contradiction,contradiction,contradiction,contradiction,contradiction,contradiction

In [6]:
df["pd"].value_counts()

pd
1.00    17226
0.80     7704
0.60     4552
0.75        7
Name: count, dtype: int64

In [7]:
df.query("pd == 0.5")

Empty DataFrame
Columns: [gold_label, annotator_labels, pairID, promptID, dataset, captionID, pd, majority_label, another_human_0, another_human_1, another_human_2, another_human_3, another_human_4]
Index: []

In [8]:
from sklearn.metrics import accuracy_score
import statistics


def accuracy_by_pd(df, another_human_label_columns, majority_label="majority_label"):
    df = df.query("pd > 0.4").copy()

    items_dataset = df["dataset"].unique()
    result = []
    # For each dataset
    for d in items_dataset:
        df_dataset = df[df["dataset"] == d]
        items_pd = df_dataset["pd"].unique()
        # For pd
        for p_d in items_pd:
            subset_df = df_dataset[df_dataset["pd"] == p_d]
            scores = []

            # For pred label
            for another_human_pred_label in another_human_label_columns:
                score = accuracy_score(subset_df[majority_label], subset_df[another_human_pred_label])
                scores.append(score)

            result.append({
                "dataset": d,
                "pd": p_d,
                "S": len(subset_df),
                "Expected_Accuracy": p_d,
                f"score_mean_{another_human_label_columns[0]}": statistics.mean(scores),
                f"score_std_{another_human_label_columns[0]}": statistics.stdev(scores),
                f"delta_expected_{another_human_label_columns[0]}": p_d - statistics.mean(scores),
                "M": "-"

            })
    return pd.DataFrame(result)


scores_df = accuracy_by_pd(df, [l for l in list(df.columns) if l.startswith("another_human")])
scores_df

,dataset,pd,S,Expected_Accuracy,score_mean_another_human_0,score_std_another_human_0,delta_expected_another_human_0,M
0,multinli_1.0_dev_matched.jsonl.small.jsonl,0.80,2457,0.80,0.805861,0.006091,-0.005861,-
1,multinli_1.0_dev_matched.jsonl.small.jsonl,1.00,5759,1.00,1.000000,0.000000,0.000000,-
2,multinli_1.0_dev_matched.jsonl.small.jsonl,0.60,1599,0.60,0.607380,0.017118,-0.007380,-
3,multinli_1.0_dev_mismatched.jsonl.small.jsonl,1.00,5984,1.00,1.000000,0.000000,0.000000,-
4,multinli_1.0_dev_mismatched.jsonl.small.jsonl,0.60,1446,0.60,0.598064,0.007471,0.001936,-
5,multinli_1.0_dev_mismatched.jsonl.small.jsonl,0.80,2402,0.80,0.802498,0.004392,-0.002498,-
6,snli_1.0_dev.jsonl.small.jsonl,0.80,2845,0.80,0.797540,0.004915,0.002460,-
7,snli_1.0_dev.jsonl.small.jsonl,1.00,5483,1.00,1.000000,0.000000,0.000000,-
8,snli_1.0_dev.jsonl.small.jsonl,0.60,1507,0.60,0.611546,0.002024,-0.011546,-
9,snli_1.0_dev.jsonl.small.jsonl,0.75,7,0.75,0.714286,0.142857,0.035714,-

In [16]:
import json


def format_latex(df, models_score_jsons_path):
    df = df.copy()
    with open(models_score_jsons_path) as f:
        models_existing_results = json.load(f)

    model_clean_names = {
        "results_mistral" : "Mistral",
        "results_mistral_large" : "Mistral-L",
        "results_llama31_8b":"Llama3.1",
        "results_sonnet" : "Sonnet",
    }


    dataset_name_dict = {
        "multinli_1.0_dev_matched.jsonl.small.jsonl": "MNLI M  $\\langle$GT = 5, L=3$\\rangle$",
        "multinli_1.0_dev_mismatched.jsonl.small.jsonl": "MNLI MM $\\langle$GT = 5, L=3$\\rangle$",
        "snli_1.0_dev.jsonl.small.jsonl": "SNLI MM $\\langle GT$ $\\in \\{5, 7\\}$, L=3$\\rangle$"
    }
    df["formatted_human_score"] = df.apply(
        lambda x: f"{x['score_mean_another_human_0']:.2f}$\\pm${x['score_std_another_human_0']:.2f}", axis=1)
    df["formatted_delta_expected_another_human"] = df.apply(
        lambda x: f"{x['delta_expected_another_human_0']:.2f}", axis=1)

    df["formatted_pd"] = df["pd"].apply(lambda x: f"{x:.2f}")
    df["formatted_expected_accuracy"] = df["Expected_Accuracy"].apply(lambda x: f"{x:.2f}")
    df["formatted_dataset"] = df["dataset"].apply(lambda x: f"{dataset_name_dict[x]}")
    model_related_cols = []
    for model, model_results in models_existing_results.items():
        model_col_name =model_clean_names.get(model, model)
        df[f"raw_{model_col_name}"] = df.apply(lambda x: float(model_results[x['dataset']].get(str(x["pd"]), {}).get("score", 0.0)), axis=1)
        df["model_name"] = model_col_name
        df[model_col_name] =df[f"raw_{model_col_name}"].apply(lambda x: f"{float(x):.2f}")
        model_related_cols.append(model_col_name)


    df_new = df.melt(id_vars=["formatted_dataset", "formatted_pd", "S","Expected_Accuracy", "formatted_expected_accuracy","formatted_human_score", "formatted_delta_expected_another_human"], value_vars=model_related_cols, var_name="model_name", value_name="model_score")

    df_new[f"delta_expected_formatted_model"] = df_new.apply(lambda x: "{:.2f}".format( x['Expected_Accuracy'] -float( x["model_score"])), axis=1)

    df_new = df_new.set_index(["formatted_dataset", "formatted_pd", "S", "formatted_expected_accuracy", "formatted_human_score", "formatted_delta_expected_another_human", "model_name"])
    df_new = df_new.sort_values(by=["formatted_dataset", "formatted_pd",  "model_name"])

    return df_new[[ "model_score", "delta_expected_formatted_model"]]


print(format_latex(scores_df, models_score_jsons_path).to_latex(index=True))

format_latex(scores_df, models_score_jsons_path)

\begin{tabular}{lllllllll}
\toprule
 &  &  &  &  &  &  & model_score & delta_expected_formatted_model \\
formatted_dataset & formatted_pd & S & formatted_expected_accuracy & formatted_human_score & formatted_delta_expected_another_human & model_name &  &  \\
\midrule
\multirow[t]{12}{*}{MNLI M  $\langle$GT = 5, L=3$\rangle$} & \multirow[t]{4}{*}{0.60} & \multirow[t]{4}{*}{1599} & \multirow[t]{4}{*}{0.60} & \multirow[t]{4}{*}{0.61$\pm$0.02} & \multirow[t]{4}{*}{-0.01} & Llama3.1 & 0.55 & 0.05 \\
 &  &  &  &  &  & Mistral & 0.50 & 0.10 \\
 &  &  &  &  &  & Mistral-L & 0.59 & 0.01 \\
 &  &  &  &  &  & Sonnet & 0.61 & -0.01 \\
\cline{2-9} \cline{3-9} \cline{4-9} \cline{5-9} \cline{6-9}
 & \multirow[t]{4}{*}{0.80} & \multirow[t]{4}{*}{2457} & \multirow[t]{4}{*}{0.80} & \multirow[t]{4}{*}{0.81$\pm$0.01} & \multirow[t]{4}{*}{-0.01} & Llama3.1 & 0.68 & 0.12 \\
 &  &  &  &  &  & Mistral & 0.63 & 0.17 \\
 &  &  &  &  &  & Mistral-L & 0.75 & 0.05 \\
 &  &  &  &  &  & Sonnet & 0.78 & 0.02 \\
\cline{2-9} \cline{3-9} \cline{4-9} \cline{5-9} \cline{6-9}
 & \multirow[t]{4}{*}{1.00} & \multirow[t]{4}{*}{5759} & \multirow[t]{4}{*}{1.00} & \multirow[t]{4}{*}{1.00$\pm$0.00} & \multirow[t]{4}{*}{0.00} & Llama3.1 & 0.75 & 0.25 \\
 &  &  &  &  &  & Mistral & 0.69 & 0.31 \\
 &  &  &  &  &  & Mistral-L & 0.87 & 0.13 \\
 &  &  &  &  &  & Sonnet & 0.89 & 0.11 \\
\cline{1-9} \cline{2-9} \cline{3-9} \cline{4-9} \cline{5-9} \cline{6-9}
\multirow[t]{12}{*}{MNLI MM $\langle$GT = 5, L=3$\rangle$} & \multirow[t]{4}{*}{0.60} & \multirow[t]{4}{*}{1446} & \multirow[t]{4}{*}{0.60} & \multirow[t]{4}{*}{0.60$\pm$0.01} & \multirow[t]{4}{*}{0.00} & Llama3.1 & 0.55 & 0.05 \\
 &  &  &  &  &  & Mistral & 0.52 & 0.08 \\
 &  &  &  &  &  & Mistral-L & 0.61 & -0.01 \\
 &  &  &  &  &  & Sonnet & 0.62 & -0.02 \\
\cline{2-9} \cline{3-9} \cline{4-9} \cline{5-9} \cline{6-9}
 & \multirow[t]{4}{*}{0.80} & \multirow[t]{4}{*}{2402} & \multirow[t]{4}{*}{0.80} & \multirow[t]{4}{*}{0.80$\pm$0.00} & \multirow[t]{4}{*}{-0.00} & Llama3.1 & 0.66 & 0.14 \\
 &  &  &  &  &  & Mistral & 0.62 & 0.18 \\
 &  &  &  &  &  & Mistral-L & 0.75 & 0.05 \\
 &  &  &  &  &  & Sonnet & 0.77 & 0.03 \\
\cline{2-9} \cline{3-9} \cline{4-9} \cline{5-9} \cline{6-9}
 & \multirow[t]{4}{*}{1.00} & \multirow[t]{4}{*}{5984} & \multirow[t]{4}{*}{1.00} & \multirow[t]{4}{*}{1.00$\pm$0.00} & \multirow[t]{4}{*}{0.00} & Llama3.1 & 0.75 & 0.25 \\
 &  &  &  &  &  & Mistral & 0.69 & 0.31 \\
 &  &  &  &  &  & Mistral-L & 0.88 & 0.12 \\
 &  &  &  &  &  & Sonnet & 0.90 & 0.10 \\
\cline{1-9} \cline{2-9} \cline{3-9} \cline{4-9} \cline{5-9} \cline{6-9}
\multirow[t]{16}{*}{SNLI MM $\langle GT$ $\in \{5, 7\}$, L=3$\rangle$} & \multirow[t]{4}{*}{0.60} & \multirow[t]{4}{*}{1507} & \multirow[t]{4}{*}{0.60} & \multirow[t]{4}{*}{0.61$\pm$0.00} & \multirow[t]{4}{*}{-0.01} & Llama3.1 & 0.54 & 0.06 \\
 &  &  &  &  &  & Mistral & 0.54 & 0.06 \\
 &  &  &  &  &  & Mistral-L & 0.64 & -0.04 \\
 &  &  &  &  &  & Sonnet & 0.61 & -0.01 \\
\cline{2-9} \cline{3-9} \cline{4-9} \cline{5-9} \cline{6-9}
 & \multirow[t]{4}{*}{0.75} & \multirow[t]{4}{*}{7} & \multirow[t]{4}{*}{0.75} & \multirow[t]{4}{*}{0.71$\pm$0.14} & \multirow[t]{4}{*}{0.04} & Llama3.1 & 0.71 & 0.04 \\
 &  &  &  &  &  & Mistral & 0.57 & 0.18 \\
 &  &  &  &  &  & Mistral-L & 0.86 & -0.11 \\
 &  &  &  &  &  & Sonnet & 0.71 & 0.04 \\
\cline{2-9} \cline{3-9} \cline{4-9} \cline{5-9} \cline{6-9}
 & \multirow[t]{4}{*}{0.80} & \multirow[t]{4}{*}{2845} & \multirow[t]{4}{*}{0.80} & \multirow[t]{4}{*}{0.80$\pm$0.00} & \multirow[t]{4}{*}{0.00} & Llama3.1 & 0.66 & 0.14 \\
 &  &  &  &  &  & Mistral & 0.62 & 0.18 \\
 &  &  &  &  &  & Mistral-L & 0.80 & 0.00 \\
 &  &  &  &  &  & Sonnet & 0.76 & 0.04 \\
\cline{2-9} \cline{3-9} \cline{4-9} \cline{5-9} \cline{6-9}
 & \multirow[t]{4}{*}{1.00} & \multirow[t]{4}{*}{5483} & \multirow[t]{4}{*}{1.00} & \multirow[t]{4}{*}{1.00$\pm$0.00} & \multirow[t]{4}{*}{0.00} & Llama3.1 & 0.65 & 0.35 \\
 &  &  &  &  &  & Mistral & 0.59 & 0.41 \\
 &  &  &  &  &  & Mistral-L & 0.81 & 0.19 \\
 &  &  &  &  &  & Sonnet & 0.80 & 0.20 \\
\cline{1-9} \cline{2-9} \cline{3-9} \cline{4-9} \cline{5-9} \cline{6-9}
\bottomrule
\end{tabular}

                                                                                                                                                                        model_score  \
formatted_dataset                                 formatted_pd S    formatted_expected_accuracy formatted_human_score formatted_delta_expected_another_human model_name
MNLI M  $\langle$GT = 5, L=3$\rangle$             0.60         1599 0.60                        0.61$\pm$0.02         -0.01                                  Llama3.1          0.55
                                                                                                                                                             Mistral           0.50
                                                                                                                                                             Mistral-L         0.59
                                                                                                                                                             Sonnet            0.61
                                                  0.80         2457 0.80                        0.81$\pm$0.01         -0.01                                  Llama3.1          0.68
                                                                                                                                                             Mistral           0.63
                                                                                                                                                             Mistral-L         0.75
                                                                                                                                                             Sonnet            0.78
                                                  1.00         5759 1.00                        1.00$\pm$0.00         0.00                                   Llama3.1          0.75
                                                                                                                                                             Mistral           0.69
                                                                                                                                                             Mistral-L         0.87
                                                                                                                                                             Sonnet            0.89
MNLI MM $\langle$GT = 5, L=3$\rangle$             0.60         1446 0.60                        0.60$\pm$0.01         0.00                                   Llama3.1          0.55
                                                                                                                                                             Mistral           0.52
                                                                                                                                                             Mistral-L         0.61
                                                                                                                                                             Sonnet            0.62
                                                  0.80         2402 0.80                        0.80$\pm$0.00         -0.00                                  Llama3.1          0.66
                                                                                                                                                             Mistral           0.62
                                                                                                                                                             Mistral-L         0.75
                                                                                                                                                             Sonnet            0.77
                                                  1.00         5984 1.00                        1.00$\pm$0.00         0.00                                   Llama3.1          0.75
                                                                                                                                                             Mistral           0.69
                                                                                                                                                             Mistral-L         0.88
                                                                                                                                                             Sonnet            0.90
SNLI MM $\langle GT$ $\in \{5, 7\}$, L=3$\rangle$ 0.60         1507 0.60                        0.61$\pm$0.00         -0.01                                  Llama3.1          0.54
                                                                                                                                                             Mistral           0.54
                                                                                                                                                             Mistral-L         0.64
                                                                                                                                                             Sonnet            0.61
                                                  0.75         7    0.75                        0.71$\pm$0.14         0.04                                   Llama3.1          0.71
                                                                                                                                                             Mistral           0.57
                                                                                                                                                             Mistral-L         0.86
                                                                                                                                                             Sonnet            0.71
                                                  0.80         2845 0.80                        0.80$\pm$0.00         0.00                                   Llama3.1          0.66
                                                                                                                                                             Mistral           0.62
                                                                                                                                                             Mistral-L         0.80
                                                                                                                                                             Sonnet            0.76
                                                  1.00         5483 1.00                        1.00$\pm$0.00         0.00                                   Llama3.1          0.65
                                                                                                                                                             Mistral           0.59
                                                                                                                                                             Mistral-L         0.81
                                                                                                                                                             Sonnet            0.80

                                                                                                                                                                        delta_expected_formatted_model
formatted_dataset                                 formatted_pd S    formatted_expected_accuracy formatted_human_score formatted_delta_expected_another_human model_name
MNLI M  $\langle$GT = 5, L=3$\rangle$             0.60         1599 0.60                        0.61$\pm$0.02         -0.01                                  Llama3.1                             0.05
                                                                                                                                                             Mistral                              0.10
                                                                                                                                                             Mistral-L                            0.01
                                                                                                                                                             Sonnet                              -0.01
                                                  0.80         2457 0.80                        0.81$\pm$0.01         -0.01                                  Llama3.1                             0.12
                                                                                                                                                             Mistral                              0.17
                                                                                                                                                             Mistral-L                            0.05
                                                                                                                                                             Sonnet                               0.02
                                                  1.00         5759 1.00                        1.00$\pm$0.00         0.00                                   Llama3.1                             0.25
                                                                                                                                                             Mistral                              0.31
                                                                                                                                                             Mistral-L                            0.13
                                                                                                                                                             Sonnet                               0.11
MNLI MM $\langle$GT = 5, L=3$\rangle$             0.60         1446 0.60                        0.60$\pm$0.01         0.00                                   Llama3.1                             0.05
                                                                                                                                                             Mistral                              0.08
                                                                                                                                                             Mistral-L                           -0.01
                                                                                                                                                             Sonnet                              -0.02
                                                  0.80         2402 0.80                        0.80$\pm$0.00         -0.00                                  Llama3.1                             0.14
                                                                                                                                                             Mistral                              0.18
                                                                                                                                                             Mistral-L                            0.05
                                                                                                                                                             Sonnet                               0.03
                                                  1.00         5984 1.00                        1.00$\pm$0.00         0.00                                   Llama3.1                             0.25
                                                                                                                                                             Mistral                              0.31
                                                                                                                                                             Mistral-L                            0.12
                                                                                                                                                             Sonnet                               0.10
SNLI MM $\langle GT$ $\in \{5, 7\}$, L=3$\rangle$ 0.60         1507 0.60                        0.61$\pm$0.00         -0.01                                  Llama3.1                             0.06
                                                                                                                                                             Mistral                              0.06
                                                                                                                                                             Mistral-L                           -0.04
                                                                                                                                                             Sonnet                              -0.01
                                                  0.75         7    0.75                        0.71$\pm$0.14         0.04                                   Llama3.1                             0.04
                                                                                                                                                             Mistral                              0.18
                                                                                                                                                             Mistral-L                           -0.11
                                                                                                                                                             Sonnet                               0.04
                                                  0.80         2845 0.80                        0.80$\pm$0.00         0.00                                   Llama3.1                             0.14
                                                                                                                                                             Mistral                              0.18
                                                                                                                                                             Mistral-L                            0.00
                                                                                                                                                             Sonnet                               0.04
                                                  1.00         5483 1.00                        1.00$\pm$0.00         0.00                                   Llama3.1                             0.35
                                                                                                                                                             Mistral                              0.41
                                                                                                                                                             Mistral-L                            0.19
                                                                                                                                                             Sonnet                               0.20